# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.XPlane(x0=1.110223024625e-16)
S2 = openmc.YPlane(y0=0.0)
S3 = openmc.ZTorus(x0=0.0,y0=0.0,z0=0.0,r=1.0,r1=0.30000000000000004,r2=0.30000000000000004)
S4 = openmc.ZTorus(x0=0.0,y0=0.0,z0=0.0,r=1.0,r1=0.2,r2=0.2)
S5 = openmc.Plane(a=0.707106781186511,b=0.707106781186584,c=-0.0,d=0.0)
S6 = openmc.XPlane(x0=-1.0000000000001454)
S7 = openmc.XPlane(x0=2.407109860380112)
S8 = openmc.YPlane(y0=-1.0)
S9 = openmc.YPlane(y0=2.407109860380112)
S10 = openmc.ZPlane(z0=-1.3)
S11 = openmc.ZPlane(z0=1.3)
S12 = openmc.Sphere(x0=0.7035549301899835,y0=0.7035549301900561,z0=0.0,r=2.7923045019990353, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S2 & +S4 & +S5 & -S3 & +S1)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-1.000, 2.407, -1.000, 2.407, -1.300, 1.300). Enclosed cells : (1)", region=(+S6 & -S7 & +S8 & -S9 & +S10 & -S11 & (-S2 | -S4 | -S5 | +S3 | -S1)))
C3 = openmc.Cell(name="", region=(-S12 & (-S6 | +S7 | -S8 | +S9 | -S10 | +S11)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
