# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.ZPlane(z0=227.183)
S2 = openmc.Plane(a=0.017452392660674526,b=0.9998476953968627,c=5.6873050481518276e-12,d=-25.800000031165396)
S3 = openmc.Plane(a=0.017452392604956506,b=0.9998476953978354,c=-6.071532165918825e-17,d=25.79999999999994)
S4 = openmc.Plane(a=-0.5806145119781811,b=0.010134655969924003,c=-0.8141155183564002,d=136.79682759906942)
S5 = openmc.ZTorus(x0=0.0,y0=0.0,z0=0.0,r=132.1,r1=343.0,r2=343.0)
S6 = openmc.ZTorus(x0=0.0,y0=0.0,z0=0.0,r=132.1,r1=341.20000000000005,r2=341.20000000000005)
S7 = openmc.YPlane(y0=0.0)
S8 = openmc.Sphere(x0=416.0,y0=0.0,z0=190.0,r=2.0)
S9 = openmc.Plane(a=-0.9998476953978354,b=0.017452392604958056,c=-0.0,d=0.0)
S10 = openmc.ZCone(x0=0.0,y0=0.0,z0=811.0576414584071,r2=0.43857033964240655)
S11 = openmc.XPlane(x0=-443.106217218376)
S12 = openmc.XPlane(x0=419.0)
S13 = openmc.YPlane(y0=-22.72250560455374)
S14 = openmc.YPlane(y0=38.06790723821015)
S15 = openmc.ZPlane(z0=144.71926821952093)
S16 = openmc.ZPlane(z0=228.18300000000013)
S17 = openmc.Sphere(x0=-12.053108609187985,y0=7.672700816828203,z0=186.45113410976055,r=442.81652691765134, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S2 & +S6 & +S9 & +S10 & -S5 & -S4 & -S3 & -S1)))
C2 = openmc.Cell(name="", region=((-S8)))
C3 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-443.106, 419.000, -22.723, 38.068, 144.719, 228.183). Enclosed cells : (1, 2)", region=(+S11 & -S12 & +S13 & -S14 & +S15 & -S16 & ((+S8) & (-S10 | -S9 | -S6 | +S5 | +S4 | +S3 | -S2 | +S1))))
C4 = openmc.Cell(name="", region=(-S17 & (-S11 | +S12 | -S13 | +S14 | -S15 | +S16)))

geometry = openmc.Geometry([C1, C2, C3, C4])
geometry.export_to_xml()
