# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.XPlane(x0=0.0)
S2 = openmc.XPlane(x0=1.0)
S3 = openmc.YPlane(y0=1.0)
S4 = openmc.YPlane(y0=0.0)
S5 = openmc.ZPlane(z0=1.0)
S6 = openmc.ZPlane(z0=0.0)
S7 = openmc.Plane(a=-0.6086182508878466,b=0.7934631842034122,c=0.0,d=0.15869263684068252)
S8 = openmc.Plane(a=-0.7714492100252415,b=-0.6362909054445386,c=0.0,d=-0.46354734753187127)
S9 = openmc.ZCylinder(x0=0.2,y0=0.2,r=0.2)
S10 = openmc.ZCylinder(x0=0.32000000000000006,y0=0.32000000000000006,r=0.1)
S11 = openmc.Plane(a=-0.7071067811865477,b=-0.7071067811865475,c=0.0,d=-0.4560838738653232)
S12 = openmc.Plane(a=0.7934631842034122,b=-0.6086182508878468,c=0.0,d=0.15869263684068247)
S13 = openmc.XPlane(x0=-1.0)
S14 = openmc.XPlane(x0=2.0)
S15 = openmc.YPlane(y0=-1.0)
S16 = openmc.YPlane(y0=2.0)
S17 = openmc.ZPlane(z0=-1.0)
S18 = openmc.ZPlane(z0=2.0)
S19 = openmc.Sphere(x0=0.5,y0=0.5,z0=0.5,r=2.6500377355803826, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S6 & +S10 & +S11 & -S9 & -S5) | (+S1 & +S6 & +S7 & +S9 & +S10 & -S5 & -S3 & -S2) | (+S4 & +S6 & +S10 & -S8 & -S7 & -S5 & -S2) | (+S4 & +S6 & +S8 & +S9 & +S12 & -S5)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-1.000, 2.000, -1.000, 2.000, -1.000, 2.000). Enclosed cells : (1)", region=(+S13 & -S14 & +S15 & -S16 & +S17 & -S18 & ((((-S10) | (((+S2) | ((+S8 | -S4 | +S7) & (+S3 | -S1 | -S9 | -S7))) & (+S9 | -S11))) & (-S12 | -S4 | -S8 | -S9)) | (+S5 | -S6))))
C3 = openmc.Cell(name="", region=(-S19 & (-S13 | +S14 | -S15 | +S16 | -S17 | +S18)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
