# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.Plane(a=-0.17566161099703348,b=0.9831182818431874,c=-0.05120002273071976,d=-918.6532756999809)
S2 = openmc.Plane(a=0.9933472808567851,b=-0.0895450095019208,c=-0.07240767147017145,d=699.2592883241467)
S3 = openmc.Plane(a=-0.6427876096867989,b=0.7660444431187602,c=2.0816681711721682e-17,d=-1042.999999999675)
S4 = openmc.Plane(a=0.7620175800347985,b=0.639408670357831,c=-0.10239999994697292,d=-45.56216504343872)
S5 = openmc.Cylinder(x0=631.1063758432001,y0=-809.6072861226,z0=86.0,r=4.45,dx=0.6427876096867989,dy=-0.7660444431187603,dz=0.0)
S6 = openmc.Cylinder(x0=635.7245002599001,y0=-816.3549434707,z0=86.08231402845001,r=4.25,dx=0.08430831801851993,dy=0.993805425049117,dz=-0.07240776654359853)
S7 = openmc.XPlane(x0=635.0265399622845)
S8 = openmc.XPlane(x0=646.5310325015785)
S9 = openmc.YPlane(y0=-824.0282617963584)
S10 = openmc.YPlane(y0=-812.3360738811081)
S11 = openmc.ZPlane(z0=80.55000000000001)
S12 = openmc.ZPlane(z0=91.42660769901295)
S13 = openmc.Sphere(x0=640.7787862319315,y0=-818.1821678387332,z0=85.98830384950648,r=10.037561885562532, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S2 & +S3 & +S4 & +S6 & -S5 & -S1)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(635.027, 646.531, -824.028, -812.336, 80.550, 91.427). Enclosed cells : (1)", region=(+S7 & -S8 & +S9 & -S10 & +S11 & -S12 & (-S2 | -S3 | -S4 | -S6 | +S5 | +S1)))
C3 = openmc.Cell(name="", region=(-S13 & (-S7 | +S8 | -S9 | +S10 | -S11 | +S12)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
