# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.XPlane(x0=-2.0)
S2 = openmc.XPlane(x0=4.0)
S3 = openmc.XPlane(x0=0.0)
S4 = openmc.XPlane(x0=-4.0)
S5 = openmc.YPlane(y0=-2.0)
S6 = openmc.YPlane(y0=-4.0)
S7 = openmc.YPlane(y0=4.0)
S8 = openmc.ZPlane(z0=0.0)
S9 = openmc.ZPlane(z0=2.0)
S10 = openmc.Plane(a=0.7907844178878555,b=-0.612094767520329,c=0.0,d=0.8668102343056046)
S11 = openmc.Plane(a=-0.16847021800364176,b=0.9857067442428328,c=0.0,d=0.1895289952540968)
S12 = openmc.XCylinder(y0=0.0,z0=7.5,r=8.5)
S13 = openmc.ZCylinder(x0=0.0,y0=0.0,r=1.5)
S14 = openmc.ZCylinder(x0=-2.0,y0=-2.0,r=2.0)
S15 = openmc.XCylinder(y0=0.0,z0=0.0,r=2.0)
S16 = openmc.Plane(a=-0.7071067811865478,b=-0.7071067811865472,c=0.0,d=1.1048543456039805)
S17 = openmc.ZPlane(z0=-0.8000000000004918)
S18 = openmc.Plane(a=-0.88260127287724,b=0.4701223171850873,c=0.0,d=2.590160457138786)
S19 = openmc.XPlane(x0=-5.0)
S20 = openmc.XPlane(x0=5.0)
S21 = openmc.YPlane(y0=-5.000000000000883)
S22 = openmc.YPlane(y0=5.000000000000002)
S23 = openmc.ZPlane(z0=-3.0000008730134575)
S24 = openmc.ZPlane(z0=3.000000000000001)
S25 = openmc.Sphere(x0=0.0,y0=-4.405364961712621e-13,z0=-4.365067285405644e-07,r=7.834768836720993, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S1 & -S5 & -S12 & -S8 & -S2) | (+S13 & -S12 & -S8 & +S5 & +S4 & -S3) | (+S8 & +S13 & +S16 & -S14 & -S9) | (+S3 & +S13 & -S12 & -S8 & +S5 & -S2) | (+S3 & +S12 & +S13 & -S15 & -S17 & -S2) | (+S6 & +S8 & +S10 & +S13 & +S14 & -S9 & -S2) | (+S8 & +S11 & +S13 & +S14 & -S10 & -S9 & -S7 & +S4 & -S2) | (+S8 & +S14 & +S18 & -S11 & -S9 & +S4)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-5.000, 5.000, -5.000, 5.000, -3.000, 3.000). Enclosed cells : (1)", region=(+S19 & -S20 & +S21 & -S22 & +S23 & -S24 & ((-S13 | +S12 | +S8 | -S5 | -S4 | +S3) & ((+S2) | (((-S13) | (((-S3) | ((-S5 | +S8 | +S12) & (+S17 | +S15 | -S12))) & (((-S10 | -S6) & (+S7 | -S11 | -S4 | +S10)) | (-S14 | +S9 | -S8)))) & (-S1 | +S5 | +S12 | +S8))) & (-S16 | -S8 | -S13 | +S14 | +S9) & (-S18 | -S8 | -S14 | +S11 | +S9 | -S4))))
C3 = openmc.Cell(name="", region=(-S25 & (-S19 | +S20 | -S21 | +S22 | -S23 | +S24)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
