# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.XPlane(x0=0.0)
S2 = openmc.XPlane(x0=0.10000000000000019)
S3 = openmc.XPlane(x0=1.0)
S4 = openmc.XPlane(x0=0.8999999999999999)
S5 = openmc.YPlane(y0=0.0)
S6 = openmc.YPlane(y0=1.0)
S7 = openmc.YPlane(y0=0.10000000000000019)
S8 = openmc.YPlane(y0=0.8999999999999999)
S9 = openmc.ZPlane(z0=0.0)
S10 = openmc.ZPlane(z0=1.0)
S11 = openmc.ZPlane(z0=0.1)
S12 = openmc.ZPlane(z0=0.9)
S13 = openmc.XPlane(x0=-1.0)
S14 = openmc.XPlane(x0=2.0)
S15 = openmc.YPlane(y0=-1.0)
S16 = openmc.YPlane(y0=2.0)
S17 = openmc.ZPlane(z0=-1.0)
S18 = openmc.ZPlane(z0=2.0)
S19 = openmc.Sphere(x0=0.5,y0=0.5,z0=0.5,r=2.6500377355803826, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S1 & +S5 & +S9 & -S10 & -S6 & -S2) | (+S4 & +S5 & +S9 & -S10 & -S6 & -S3) | (+S2 & +S5 & +S9 & -S10 & -S7 & -S4) | (+S2 & +S7 & +S9 & -S11 & -S8 & -S4) | (+S2 & +S7 & +S12 & -S10 & -S8 & -S4) | (+S2 & +S8 & +S9 & -S10 & -S6 & -S4)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-1.000, 2.000, -1.000, 2.000, -1.000, 2.000). Enclosed cells : (1)", region=(+S13 & -S14 & +S15 & -S16 & +S17 & -S18 & (((-S9) | (((+S10) | (((-S5) | (((+S6) | ((+S2 | -S1) & (-S4 | +S3))) & (+S7 | -S2 | +S4))) & (-S8 | -S2 | +S6 | +S4))) & (+S11 | -S2 | -S7 | +S8 | +S4))) & (-S12 | -S2 | -S7 | +S10 | +S8 | +S4))))
C3 = openmc.Cell(name="", region=(-S19 & (-S13 | +S14 | -S15 | +S16 | -S17 | +S18)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
