# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.ZPlane(z0=0.0)
S2 = openmc.ZPlane(z0=0.4)
S3 = openmc.Plane(a=-0.7071067811865476,b=0.7071067811865476,c=0.0,d=0.0)
S4 = openmc.Plane(a=0.7071067811865476,b=0.7071067811865476,c=0.0,d=4.999999999999948)
S5 = openmc.Plane(a=-0.7071067811865476,b=0.7071067811865476,c=0.0,d=0.5000000000000372)
S6 = openmc.Sphere(x0=0.0,y0=0.30000000000000004,z0=0.1,r=0.5)
S7 = openmc.Plane(a=0.6194622634933904,b=0.7497355987559993,c=0.23272953414989817,d=0.2481936330417896)
S8 = openmc.XPlane(x0=-1.008963833247093)
S9 = openmc.XPlane(x0=4.535533905932701)
S10 = openmc.YPlane(y0=-0.6102084238345253)
S11 = openmc.YPlane(y0=4.88908729652605)
S12 = openmc.ZPlane(z0=-1.0000000000000124)
S13 = openmc.ZPlane(z0=1.4000000000000445)
S14 = openmc.Sphere(x0=1.763285036342804,y0=2.139439436345763,z0=0.20000000000001608,r=4.166537964160894, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S1 & +S3 & +S6 & +S7 & -S5 & -S4 & -S2)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-1.009, 4.536, -0.610, 4.889, -1.000, 1.400). Enclosed cells : (1)", region=(+S8 & -S9 & +S10 & -S11 & +S12 & -S13 & (-S1 | -S3 | -S6 | -S7 | +S5 | +S4 | +S2)))
C3 = openmc.Cell(name="", region=(-S14 & (-S8 | +S9 | -S10 | +S11 | -S12 | +S13)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
