# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.XPlane(x0=-1.1100000000000002e-16)
S2 = openmc.YPlane(y0=2.0)
S3 = openmc.YPlane(y0=0.0)
S4 = openmc.ZTorus(x0=0.0,y0=2.0,z0=0.0,r=1.0,r1=0.30000000000000004,r2=0.30000000000000004)
S5 = openmc.ZTorus(x0=0.0,y0=2.0,z0=0.0,r=1.0,r1=0.2,r2=0.2)
S6 = openmc.ZTorus(x0=0.0,y0=0.0,z0=0.0,r=1.0,r1=0.30000000000000004,r2=0.30000000000000004)
S7 = openmc.ZTorus(x0=0.0,y0=0.0,z0=0.0,r=1.0,r1=0.2,r2=0.2)
S8 = openmc.Plane(a=-0.7071067811865109,b=-0.7071067811865841,c=0.0,d=-1.4142135623731684)
S9 = openmc.Plane(a=0.7071067811868033,b=0.7071067811862918,c=-0.0,d=0.0)
S10 = openmc.XPlane(x0=-2.407109860380112)
S11 = openmc.XPlane(x0=2.407109860380112)
S12 = openmc.YPlane(y0=-1.0000000000005822)
S13 = openmc.YPlane(y0=3.0)
S14 = openmc.ZPlane(z0=-1.3)
S15 = openmc.ZPlane(z0=1.3)
S16 = openmc.Sphere(x0=0.0,y0=0.9999999999997091,z0=0.0,r=3.456607971160443, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((-S1 & -S2 & +S5 & +S8 & -S4) | (+S3 & +S7 & +S9 & -S6 & +S1)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-2.407, 2.407, -1.000, 3.000, -1.300, 1.300). Enclosed cells : (1)", region=(+S10 & -S11 & +S12 & -S13 & +S14 & -S15 & ((-S8 | -S5 | +S4 | +S2 | +S1) & (-S9 | -S7 | +S6 | -S3 | -S1))))
C3 = openmc.Cell(name="", region=(-S16 & (-S10 | +S11 | -S12 | +S13 | -S14 | +S15)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
