# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.Plane(a=0.7620175800347986,b=0.639408670357831,c=-0.10239999994697294,d=-45.562165043517496)
S2 = openmc.Plane(a=0.6427876096867989,b=-0.7660444431187603,c=0.0,d=1023.0000000002282)
S3 = openmc.Plane(a=-0.6427876096867989,b=0.7660444431187603,c=0.0,d=-1030.9999999997092)
S4 = openmc.Cylinder(x0=607.829415753,y0=-781.8668853102,z0=86.0,r=4.25,dx=0.6427876096867989,dy=-0.7660444431187603,dz=0.0)
S5 = openmc.Cylinder(x0=631.1063758432001,y0=-809.6072861226,z0=86.0,r=4.45,dx=0.6427876096867989,dy=-0.7660444431187603,dz=0.0)
S6 = openmc.XPlane(x0=627.9173114190959)
S7 = openmc.XPlane(x0=638.8175811853785)
S8 = openmc.YPlane(y0=-814.8357284789583)
S9 = openmc.YPlane(y0=-803.5540626255882)
S10 = openmc.ZPlane(z0=80.55000000000001)
S11 = openmc.ZPlane(z0=91.42660769901653)
S12 = openmc.Sphere(x0=633.3674463022371,y0=-809.1948955522732,z0=85.98830384950827,r=9.73542392303797, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S1 & +S2 & +S3 & +S4 & -S5)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(627.917, 638.818, -814.836, -803.554, 80.550, 91.427). Enclosed cells : (1)", region=(+S6 & -S7 & +S8 & -S9 & +S10 & -S11 & (-S1 | -S2 | -S3 | -S4 | +S5)))
C3 = openmc.Cell(name="", region=(-S12 & (-S6 | +S7 | -S8 | +S9 | -S10 | +S11)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
