# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.Plane(a=-0.6427876096867989,b=0.7660444431187603,c=0.0,d=-1030.999999999709)
S2 = openmc.Plane(a=0.7620175800347986,b=0.639408670357831,c=-0.10239999994697294,d=-45.56216504351753)
S3 = openmc.Plane(a=-0.17566161099703348,b=0.9831182818431874,c=-0.05120002273071976,d=-918.6532756999807)
S4 = openmc.Cylinder(x0=631.1063758432001,y0=-809.6072861226,z0=86.0,r=4.45,dx=0.6427876096867989,dy=-0.7660444431187603,dz=0.0)
S5 = openmc.Cylinder(x0=634.4086834136001,y0=-813.5428230332,z0=86.0,r=4.25,dx=-0.423660491523819,dy=0.9054332524086132,dz=-0.026503081982228678)
S6 = openmc.Plane(a=0.9024181340849036,b=0.41935445537818494,c=-0.09891082867505972,d=222.83276150263137)
S7 = openmc.XPlane(x0=632.592510012262)
S8 = openmc.XPlane(x0=642.6957218626895)
S9 = openmc.YPlane(y0=-819.4575165637791)
S10 = openmc.YPlane(y0=-809.6824181700947)
S11 = openmc.ZPlane(z0=80.55000000000001)
S12 = openmc.ZPlane(z0=91.42660769901653)
S13 = openmc.Sphere(x0=637.6441159374758,y0=-814.5699673669369,z0=85.98830384950827,r=9.064925894430111, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S2 & +S3 & +S5 & +S6 & -S4 & -S1)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(632.593, 642.696, -819.458, -809.682, 80.550, 91.427). Enclosed cells : (1)", region=(+S7 & -S8 & +S9 & -S10 & +S11 & -S12 & (-S2 | -S3 | -S5 | -S6 | +S4 | +S1)))
C3 = openmc.Cell(name="", region=(-S13 & (-S7 | +S8 | -S9 | +S10 | -S11 | +S12)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
