##############################
# Module to write MCDC input #
##############################

import logging
from pathlib import Path

import FreeCAD

from ..code_version import *
from ..utils.functions import SurfacesDict
from .functions import change_surf_sign, mcdc_surface, write_mcdc_region

logger = logging.getLogger("general_logger")


class MCDCInput:
    def __init__(self, Meta, Surfaces, options, tolerances, numeric_format):
        self.Cells = Meta
        self.options = options
        self.tolerances = tolerances
        self.numeric_format = numeric_format

        self.get_surface_table()
        self.simplify_planes(Surfaces)
        self.Surfaces = self.sorted_surfaces(Surfaces)

        self.Materials = set()

    def write_py(self, filename):
        logger.info(f"write MCDC python script {filename}")

        # get all the materials present in the model
        for cell in self.Cells:
            if cell.Material != 0:
                self.Materials.add(cell.Material)

        Path(filename).parent.mkdir(parents=True, exist_ok=True)
        with open(file=filename, mode="w", encoding="utf-8") as self.inpfile:
            self.write_header()

            if len(self.Materials) > 0:
                self.inpfile.write("# Materials setup\n")
                self.write_materials()
            self.inpfile.write("\n")

            self.inpfile.write("# Surface setup\n")
            self.write_surface_block()
            self.inpfile.write("\n")

            self.inpfile.write("# Cell definition \n")
            self.write_cell_block()
        return

    def write_header(self):
        Header = '''
        # MCDC input file generated by GEOUNED
        import mcdc
        import numpy as np
        '''
        self.inpfile.write(Header)

    def write_materials(self):

        matList = tuple(sorted(self.Materials))
        strMat = []
        for m in matList:
            material = f"m{m} = None # TODO: replace with real material values\n"
            self.inpfile.write(material)

        self.inpfile.write(collect)

    def write_surface_block(self):

        for surf in self.Surfaces[:-1]:
            self.write_surfaces(surf)
        self.write_surfaces(self.Surfaces[-1], boundary=True)
        self.inpfile.write("\n")

    def write_surfaces(self, surface, boundary=False):

        surfType, coeffs = mcdc_surface(
            surface.Type,
            surface.Surf,
            self.tolerances,
            self.numeric_format)
        
        if not boundary:
            line = f"s{surface.Index} = mcdc.Surface.{surfType}({coeffs})\n"
        else:
            line = f"s{surface.Index} = mcdc.Surface.{surfType}({coeffs}, bc=\"vacuum\")\n"

        self.inpfile.write(line)
        return

    def write_cell_block(self):

        cellNames = []
        for i, cell in enumerate(self.Cells):
            if cell.MatInfo == "Graveyard":
                continue
            self.write_cells(cell)
            if cell.__id__ is None:
                continue

        return

    def write_cells(self, cell):
        index = cell.label
        cellName = ". ".join(cell.Comments.splitlines())
        if cell.__id__ is None:
            return

        if cell.Material == 0:
            mcCell = '{} = mcdc.Cell(fill=None, region={})\n'.format(
                cellName,
                write_mcdc_region(cell.Definition, self.options),
            )
        else:
            matName = f"m{cell.Material}"
            mcCell = '{} = mcdc.Cell(fill={}, region={})\n'.format(
                cellName,
                matName,
                write_mcdc_region(cell.Definition, self.options),
            )
        self.inpfile.write(mcCell)
        return

    def get_surface_table(self):
        self.surfaceTable = {}
        self.__solidCells__ = 0
        self.__cells__ = 0
        self.__materials__ = set()

        for i, CellObj in enumerate(self.Cells):
            if CellObj.__id__ is None:
                continue
            self.__cells__ += 1
            if CellObj.Material != 0:
                self.__materials__.add(CellObj.Material)

            surf = CellObj.Definition.get_surfaces_numbers()
            if not CellObj.Void:
                self.__solidCells__ += 1
            for index in surf:
                if index in self.surfaceTable.keys():
                    self.surfaceTable[index].add(i)
                else:
                    self.surfaceTable[index] = {i}
        return

    def simplify_planes(self, Surfaces):

        for p in Surfaces["PX"]:
            if p.Surf.Axis[0] < 0:
                p.Surf.Axis = FreeCAD.Vector(1, 0, 0)
                self.change_surf_sign(p)

        for p in Surfaces["PY"]:
            if p.Surf.Axis[1] < 0:
                p.Surf.Axis = FreeCAD.Vector(0, 1, 0)
                self.change_surf_sign(p)

        for p in Surfaces["PZ"]:
            if p.Surf.Axis[2] < 0:
                p.Surf.Axis = FreeCAD.Vector(0, 0, 1)
                self.change_surf_sign(p)
        return