##############################
# Module to write MCDC input #
##############################

import logging
from pathlib import Path

import FreeCAD

from ..code_version import *
from ..utils.functions import SurfacesDict
from .functions import change_surf_sign, mcdc_surface, write_mcdc_region

logger = logging.getLogger("general_logger")


class MCDCInput:
    def __init__(self, Meta, Surfaces, options, tolerances, numeric_format):
        self.Cells = Meta
        self.options = options
        self.tolerances = tolerances
        self.numeric_format = numeric_format

        self.get_surface_table()
        self.simplify_planes(Surfaces)
        self.Surfaces = self.sorted_surfaces(Surfaces)

        self.Materials = set()

    def write_py(self, filename):
        logger.info(f"write MCDC python script {filename}")

        # get all the materials present in the model
        for cell in self.Cells:
            if cell.Material != 0:
                self.Materials.add(cell.Material)

        Path(filename).parent.mkdir(parents=True, exist_ok=True)
        with open(file=filename, mode="w", encoding="utf-8") as self.inpfile:
            self.write_header()

            if len(self.Materials) > 0:
                self.inpfile.write("# Materials setup\n")
                self.write_materials()
            self.inpfile.write("\n")

            self.inpfile.write("# Surface setup\n")
            self.write_surface_block()
            self.inpfile.write("\n")

            self.inpfile.write("# Cell definition \n")
            self.write_cell_block()
        return

    def write_header(self):
        Header = '''
        # MCDC input file generated by GEOUNED
        import mcdc
        import numpy as np
        '''
        self.inpfile.write(Header)

    def write_materials(self):

        matList = tuple(sorted(self.Materials))
        strMat = []
        for m in matList:
            material = f"M{m} = None # TODO: replace with real material values\n"
            self.inpfile.write(material)

        self.inpfile.write(collect)

    def write_surface_block(self):

        for surf in self.Surfaces[:-1]:
            self.write_surfaces(surf)
        self.write_surfaces(self.Surfaces[-1], boundary=True)
        self.inpfile.write("\n")

    def write_surfaces(self, surface, boundary=False):

        surfType, coeffs = mcdc_surface(
            surface.Type,
            surface.Surf,
            self.tolerances,
            self.numeric_format)
        
        if not boundary:
            line = f"s{surface.Index} = mcdc.Surface.{surfType}({coeffs})\n"
        else:
            line = f"s{surface.Index} = mcdc.Surface.{surfType}({coeffs}, bc=\"vacuum\")\n"

        return line