# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.ZPlane(z0=10.0)
S2 = openmc.ZPlane(z0=0.0)
S3 = openmc.ZCylinder(x0=0.0,y0=0.0,r=2.5)
S4 = openmc.ZCylinder(x0=0.0,y0=0.0,r=2.0)
S5 = openmc.ZTorus(x0=0.0,y0=0.0,z0=0.0,r=2.25,r1=0.25,r2=0.25)
S6 = openmc.XPlane(x0=-3.705980500730985)
S7 = openmc.XPlane(x0=3.705980500730985)
S8 = openmc.YPlane(y0=-3.705980500730985)
S9 = openmc.YPlane(y0=3.705980500730985)
S10 = openmc.ZPlane(z0=-1.1775)
S11 = openmc.ZPlane(z0=11.0)
S12 = openmc.Sphere(x0=0.0,y0=0.0,z0=4.91125,r=8.194445342434282, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S2 & +S4 & +S5 & -S3 & -S1)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-3.706, 3.706, -3.706, 3.706, -1.177, 11.000). Enclosed cells : (1)", region=(+S6 & -S7 & +S8 & -S9 & +S10 & -S11 & (-S2 | -S4 | -S5 | +S3 | +S1)))
C3 = openmc.Cell(name="", region=(-S12 & (-S6 | +S7 | -S8 | +S9 | -S10 | +S11)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
