#!/usr/bin/python

# Path to GEOUNED Package
import sys

geo_path="/opt/geouned/v1.0/"

sys.path.append(geo_path)

# linux distribution
sys.path.append('/usr/lib64/freecad/lib64/')

from geouned import CadToCsg
from geouned.GEOReverse import reverse

runReverse = False
if len(sys.argv) < 2 :
   inifile = 'config.ini'

elif len(sys.argv) == 2 :
   if sys.argv[1] == '-r':
      runReverse = True
      inifile = 'configReverse.ini'
   else:
      inifile = sys.argv[1]

elif len(sys.argv) == 3:
   if   sys.argv[1] == '-r':
      runReverse = True
      inifile = sys.argv[2]
   elif sys.argv[2] == '-r':
      runReverse = True
      inifile = sys.argv[1]
   else:
      raise ValueError('Bad option')
else:
   raise ValueError('Too many input arguments')


if not runReverse :
  GEO = CadToCsg()
  GEO.set_configuration(inifile)
  GEO.Start()

else:
  print(inifile)
  reverse(inifile)
