# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.Plane(a=0.49999999999984,b=-0.7071067811867737,c=0.49999999999984,d=1.0085786437625637)
S2 = openmc.Cylinder(x0=0.1,y0=0.2,z0=0.2,r=0.2,dx=0.4999999999998401,dy=-0.7071067811867738,dz=0.4999999999998401)
S3 = openmc.Sphere(x0=0.0,y0=0.30000000000000004,z0=0.1,r=0.5)
S4 = openmc.Plane(a=0.5309437459891384,b=-0.6604525688677342,c=0.5309436343634155,d=-0.1450414072239787)
S5 = openmc.XPlane(x0=-0.9481611689853576)
S6 = openmc.XPlane(x0=1.7732050807569064)
S7 = openmc.YPlane(y0=-1.6485281374240381)
S8 = openmc.YPlane(y0=1.19013257202797)
S9 = openmc.ZPlane(z0=-0.8363969626101307)
S10 = openmc.ZPlane(z0=1.873205080756906)
S11 = openmc.Sphere(x0=0.4125219558857744,y0=-0.22919778269803404,z0=0.5184040590733877,r=2.4355248569749888, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S3 & +S4 & -S2 & -S1)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-0.948, 1.773, -1.649, 1.190, -0.836, 1.873). Enclosed cells : (1)", region=(+S5 & -S6 & +S7 & -S8 & +S9 & -S10 & (-S3 | -S4 | +S2 | +S1)))
C3 = openmc.Cell(name="", region=(-S11 & (-S5 | +S6 | -S7 | +S8 | -S9 | +S10)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
