# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.Plane(a=0.4999999999998401,b=0.4999999999998401,c=0.7071067811867738,d=0.7742640687120063)
S2 = openmc.Plane(a=-0.14644660940702836,b=0.8535533905931653,c=-0.5000000000000968,d=0.7707106781185744)
S3 = openmc.Plane(a=0.8535533905931653,b=-0.14644660940702836,c=-0.5000000000000968,d=0.7707106781185742)
S4 = openmc.Plane(a=-0.49999999999817374,b=-0.499999999998272,c=-0.7071067811890608,d=-0.5242640687090744)
S5 = openmc.ZTorus(x0=0.0,y0=0.0,z0=0.0,r=1.0,r1=0.2,r2=0.2)
S6 = openmc.Plane(a=0.707106781186521,b=0.707106781186574,c=-0.0,d=0.0)
S7 = openmc.ZCone(x0=0.0,y0=0.0,z0=-0.5956690385938915,r2=5.137022123715908)
S8 = openmc.XPlane(x0=-0.5944896372073454)
S9 = openmc.XPlane(x0=2.144649005138421)
S10 = openmc.YPlane(y0=-0.5944896372072886)
S11 = openmc.YPlane(y0=2.144649005138467)
S12 = openmc.ZPlane(z0=-1.4000000000000707)
S13 = openmc.ZPlane(z0=1.0)
S14 = openmc.Sphere(x0=0.7750796839655378,y0=0.7750796839655891,z0=-0.20000000000003537,r=2.3240426926233977, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((+S5 & +S6 & +S7 & -S2 & -S4 & -S3 & -S1)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-0.594, 2.145, -0.594, 2.145, -1.400, 1.000). Enclosed cells : (1)", region=(+S8 & -S9 & +S10 & -S11 & +S12 & -S13 & (-S5 | -S6 | -S7 | +S2 | +S4 | +S3 | +S1)))
C3 = openmc.Cell(name="", region=(-S14 & (-S8 | +S9 | -S10 | +S11 | -S12 | +S13)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
