# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.ZTorus(x0=0.0,y0=0.0,z0=0.0,r=1.0,r1=0.2,r2=0.2)
S2 = openmc.XPlane(x0=-2.298870640350873)
S3 = openmc.XPlane(x0=2.298870640350873)
S4 = openmc.YPlane(y0=-2.298870640350873)
S5 = openmc.YPlane(y0=2.298870640350873)
S6 = openmc.ZPlane(z0=-1.2000000000000002)
S7 = openmc.ZPlane(z0=1.2000000000000002)
S8 = openmc.Sphere(x0=0.0,y0=0.0,z0=0.0,r=3.5347985493938263, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="", region=((-S1)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-2.299, 2.299, -2.299, 2.299, -1.200, 1.200). Enclosed cells : (1)", region=(+S2 & -S3 & +S4 & -S5 & +S6 & -S7 & (+S1)))
C3 = openmc.Cell(name="", region=(-S8 & (-S2 | +S3 | -S4 | +S5 | -S6 | +S7)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
