# openMC geometry script generated by GEOUNED
import openmc

###############################################################################
# Define problem geometry
###############################################################################


# Surface setup
S1 = openmc.Plane(a=0.4067366430758187,b=0.0,c=0.9135454576425928,d=0.7915244647198181)
S2 = openmc.Plane(a=0.8535533905931653,b=0.1464466094070284,c=-0.5000000000000968,d=-0.12928932188137504)
S3 = openmc.Plane(a=0.04684610648168622,b=-0.29883623873010334,c=0.9531538935183297,d=0.22244314615620425)
S4 = openmc.Plane(a=0.1464466094070284,b=0.8535533905931653,c=0.5000000000000968,d=0.12928932188137504)
S5 = openmc.Plane(a=0.49999999999984,b=-0.49999999999984,c=0.7071067811867737,d=0.3828427124747348)
S6 = openmc.ZCylinder(x0=0.0,y0=0.0,r=0.2)
S7 = openmc.XPlane(x0=-1.2000000000000004)
S8 = openmc.XPlane(x0=1.200000000000049)
S9 = openmc.YPlane(y0=-1.2000000000000262)
S10 = openmc.YPlane(y0=1.2000000000000262)
S11 = openmc.ZPlane(z0=-0.8408113492937)
S12 = openmc.ZPlane(z0=1.9554771314691075)
S13 = openmc.Sphere(x0=2.4336088699783433e-14,y0=0.0,z0=0.5573328910877037,r=2.242795918605849, boundary_type="vacuum")

# Cell definition 
C1 = openmc.Cell(name="/Slice.0041", region=((-S6 & +S3 & -S1 & -S2) | (+S2 & -S6 & +S3 & -S4) | (+S2 & +S3 & +S4 & -S6 & -S5)))
C2 = openmc.Cell(name="Automatic Generated Void Cell. Enclosure(-1.200, 1.200, -1.200, 1.200, -0.841, 1.955). Enclosed cells : (1)", region=(+S7 & -S8 & +S9 & -S10 & +S11 & -S12 & (((-S2 | +S4) & (+S2 | +S1) & (+S5 | -S2 | -S4)) | (-S3 | +S6))))
C3 = openmc.Cell(name="", region=(-S13 & (-S7 | +S8 | -S9 | +S10 | -S11 | +S12)))

geometry = openmc.Geometry([C1, C2, C3])
geometry.export_to_xml()
