name: documentation

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  testing:
    name: Documentation
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: checkout actions
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: install dependencies
        run: conda install -c conda-forge freecad -y

      - name: install package
        run: |
          pip install --upgrade pip
          pip install .[docs]
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
